[advisories]
version = 2

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
]
exceptions = [
    { allow = ["AGPL-3.0"], crate = "tacowrap" },
    { allow = ["Unicode-DFS-2016"], crate = "unicode-ident" },
]

[bans]
skip-tree = [
    { name = "windows-sys", version = "0.48", depth = 3 },
]
